### ISSUE TITLE
Preparation for v3.0.0

### ISSUE THREAD

**Issue by acelaya** [shlinkio/shlink#1014]
* [x] #1275
* [x] Remove default GeoLite2 license key and revoke it. Do not try to geolocate visits when no license key is provided.
* [x] Disable default GeoLite2 license key.
* [x] ~Drop support for PHP 7.4 (use some of the cool PHP 8 features).~ This will actually happen for version 2.8 https://github.com/shlinkio/shlink/issues/1046
* [x] #1276
* [x] #1277
* [x] Remove URL validation config option. Only rely in the `validateUrl` param. If it's sent with value `true`, the URL is validated, otherwise it's not.
* [x] ~Enable composer `platform-checks`: This will check all required extensions are installed when running shlink, throwing an error otherwise.~ Not possible, as there are features that require specific platform deps, and forcing to install those even if you are not using the features, will cause friction.
* [x] #1283
* [x] Make ~USE_HTTPS~ `IS_HTTPS_ENABLED` default to true.
* [x] ~Re-consider domain falling back behavior. It was done the way it is for BC. Might be the moment to change it.~ This can't be changed, as it would make it hard to update to v3.0 from older versions but retaining links behavior.
* [x] #1300
* [x] #1299
* [x] Check pending `TODO`s and `FIXME`s.
* [x] #1347
* [x] Review README for outdated info
* [x] Ensure only known env vars can be loaded from generated_config.php
