### ISSUE TITLE
Allow sending visits to a matomo analytics instance

### ISSUE THREAD

**Issue by acelaya** [shlinkio/shlink#1798]
https://github.com/matomo-org/matomo-php-tracker

---

FAQ:

- How to generate the [API token](https://matomo.org/faq/general/faq_114/) and get the [Site ID](https://matomo.org/faq/general/faq_19212/). Instructions with screenshot/s.
- How to find the site ID: https://matomo.org/faq/general/faq_19212/
- Matomo tracks unique visits in intervals of 30 min. New visits from the same visitor within that interval are considered actions of the same visit: https://matomo.org/faq/general/faq_36/#:~:text=If%20a%20visitor%20enters%20to,it%20in%20a%20new%20Visit.
  This can make visits in Shlink and matomo not match, so it should be documented how it works, and how to change it.
- Matomo uses IP + User agent to determine unique visitors: https://matomo.org/faq/general/faq_43/#:~:text=Unique%20visitors%20are%20determined%20using,will%20detect%20two%20unique%20visitors.
- Matomo obfuscates IP addresses by discarding last two octets: https://forum.matomo.org/t/how-matomo-anonymises-ip-addresses/34006/2

TODO

- [x] Visits should be sent using a background job when possible.
- [ ] Detect if token is invalid. Right now it fails to track visit, but Matomo does not return an error (see https://github.com/matomo-org/matomo-php-tracker/issues/127)
- [ ] Detect if site ID is invalid. Right now it fails to track visit, but Matomo does not return an error (see https://github.com/matomo-org/matomo-php-tracker/issues/127)
- [x] Make sure there's a reasonable timeout. If the matomo instance goes away, it should not have a big impact on visitors, specially when not using an async runtime.
- [x] Make dev env more straightforward. Right now you need to go over the installation process and generate some info manually.
- [x] [Document integration with matomo](https://github.com/shlinkio/shlink.io/issues/475)

Nice to have (for future versions):

- [ ] Support different site IDs per domain
- [ ] Add console command to send existing visits to matomo
- [ ] Allow customizing the timeout (`MATOMO_TIMEOUT`)

**Comment by acelaya** [comment]
Send a visit to matomo:

```php
$matomoToken = '...'; // Must be admin/superuser
$matomoSiteId = '3';
$matomoUrl = 'http://shlink_matomo';

// Create a new MatomoTracker on every request, because it infers request info during construction
$tracker = new MatomoTracker($matomoSiteId, $matomoUrl);
$tracker->setTokenAuth($matomoToken);

dump(
    $tracker
        ->setUrl('http://localhost:8000/orphan') // Set absolute short URL for the visit to be tracked
        ->setCity('Zaragoza')
        ->setCountry('Spain')
        ->setRegion('Aragón')
        ->setLatitude(1)
        ->setLongitude(1)
        ->setIp('192.168.1.2') // Set not obfuscated, as matomo handles obfuscation on itself
        ->setUserAgent('foo')
        ->setCustomTrackingParameter('type', VisitType::INVALID_SHORT_URL->value)
        ->setCustomTrackingParameter('orphan', 'true') // Set only for orphan visits?

        // Leave title empty to avoid an action to be tracked
        ->doTrackPageView(''),
);
```

**Comment by acelaya** [comment]
Response from matomo when invalid token is provided:

```
^ b"GIF89a\x01\x00\x01\x00€\x00\x00\x00\x00\x00\x00\x00\x00!ù\x04\x01\x00\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;This resource is part of Matomo. Keep full control of your data with the leading free and open source <a href='https://matomo.org' target='_blank' rel='noopener noreferrer nofollow'>web analytics & conversion optimisation platform</a>.<br>\nThis file is the endpoint for the Matomo tracking API. If you want to access the Matomo UI or use the Reporting API, please use <a href='index.php'>index.php</a> instead."
```
