### ISSUE TITLE
Dynamic rule-based redirects

### ISSUE THREAD

**Issue by acelaya** [shlinkio/shlink#1914]
### Summary

[This RFC](https://github.com/shlinkio/shlink/discussions/1912) describes how dynamic redirects could be improved to support multiple combinations of rules, and then, be able to add more rules in future.

The first iteration should consist on preparing the base implementation for this to work, and potentially migrate device-specific long URLs to be the first supported redirect rule.

### Use case

Supporting multiple dynamic redirect rules has been requested in the past, specially since device-specific redirects were implemented.

---

- [x] [Design persistence model](https://github.com/shlinkio/shlink/issues/1914#issuecomment-1962327416):
    - https://github.com/shlinkio/shlink/pull/2022
    - https://github.com/shlinkio/shlink/pull/2035
- [x] [Design logic for dynamic redirects](https://github.com/shlinkio/shlink/issues/1914#issuecomment-1962329907): https://github.com/shlinkio/shlink/pull/2024
- [x] [Design API model](https://github.com/shlinkio/shlink/issues/1914#issuecomment-1963021599):
    - https://github.com/shlinkio/shlink/pull/2031
    - https://github.com/shlinkio/shlink/pull/2033
    - [x] Validate conditions during creation/edition. The key and value should validate differently depending on the type of the condition.
- [x] [Allow handling rules and conditions from the CLI]: https://github.com/shlinkio/shlink/pull/2038(https://github.com/shlinkio/shlink/issues/1914#issuecomment-1967429059)
- [x] Migrate device-specific long URLs to rules: https://github.com/shlinkio/shlink/pull/2030
- [x] Do some basic benchmarking to see the impact of rules on redirections, and the impact of the new logic when there are no rules, compared to previous metrics
- [x] Evaluate if conditions should be eagerly loaded with their corresponding rules, or it is more performant to lazy load them so that once one matches we don't load any more.

**Comment by acelaya** [comment]
### Preliminary persistence model

```mermaid
erDiagram
    short_urls 1--many(0) short_url_redirect_rules : has
    short_url_redirect_rules many(1)--many(1) redirect_conditions : has
    short_urls {
        string long_url
    }
    short_url_redirect_rules {
        int short_url_id
        int priority
        string long_url
    }
    redirect_conditions {
        string name UK "Example: device-android, query-foo-bar, language-en-US"
        string type "enum(device, language, query...)"
        string match_key "optional/nullable"
        string match_value
    }
```

* `redirect_conditions`:
  * The name will be generated combining type+match_key+match_value, or just type+match_value if match_key is null.
  * The name will be used as the public way to identify conditions, avoiding the autonumeric primary key to be exposed.

**Comment by acelaya** [comment]
### Dynamic redirects

Short URL redirects currently work like this:

1. `RedirectAction` is dispatched if an existing short URL could be matched.
2. `ShortUrlRedirectionBuilder` is invoked, and tries to resolve the long URL to redirect to.
  * Using the User-Agent header it tries to match a device long URL
  * If it cannot match, it falls back to the regular long URL 
3. Depending on how Shlink is configured, it appends extra path and/or query params, if needed.

With the new system, we can keep the `ShortUrlRedirectionBuilder`, As its only public method already receives the ShortUrl and the Request object, which will be needed to match rules and conditions.

**Comment by acelaya** [comment]
### API model

I'm thinking the simplest solution is to allow editing or listing rules and conditions always linked to a short URL, so the preliminary endpoints could look like this:

- `GET /short-urls/{shortCode}/redirect-rules[?domain={domain}]`
- `PATCH /short-urls/{shortCode}/redirect-rules[?domain={domain}]`

Then in the UI, we'll call the first one just before editing a short URL, and the second one after creating/editing a short URL succeeded.

**Comment by acelaya** [comment]
### CLI handling

I have realized device long URLs were never supported in the CLI, which I guess it's good now, as it's one less thing to change.

For redirect rules, I think a set of new commands is the best approach. Something like `short-url:list-rules` and `short-url:set-rules`.
