### ISSUE TITLE
Make shlink clusterizable

### ISSUE THREAD

**Issue by acelaya** [shlinkio/shlink#305]
Few things would need to be shared.
- [x] database creation (with a shared lock) -> #440
    * Check if database exists. If not, create it.
    * Check if tables exist. If they do, exit gracefully.
    * Run schema creation command.
    * All previous steps should be wrapped in a lock. 
- [x] migrations (with a shared lock) -> #305 (~~#439~~)
    * Run migrations command wrapped in a lock.
- [x] locking system (should be shared) #444 
    * Support redis.
    * Preprocess config to allow setting if redis should be used for locks which will translate into service overwritting.
    * Add redis container to development.
- [x] ~cache~ (not used for anything that needs to be shared)
    * Use shared redis for caching.
