### ISSUE TITLE
Multi-domain improvements

### ISSUE THREAD

**Issue by acelaya** [shlinkio/shlink#552]
Improvements for multi-domain support:

- [x] Command and rest action to list existing domains (authority, isDefault) https://github.com/shlinkio/shlink/issues/838
- [ ] #1161
- [x] Command to define domain-specific not found redirects. (https://github.com/shlinkio/shlink/issues/943)
    - Improvements:
        - [x] Make domains listing work properly with specifications when API keys are involved (currently, they are not returned 
        - [x] Expose behavior through a rest action that takes into account the API key permissions. 
        - [x] Allow listing domains even if not used by any short URL, in order to display the redirects.
        - [x] Validate domains and URLs when filtering by domain API key, for a domain that has not been used on any short URL).
        - [x] Allow editting the redirects for default domain in the same way.
- [ ] #1160
- [ ] #1162

**Comment by admecoach** [comment]
I was able to add one domain to nginx but adding a 3rd domain, no  luck. For multi-domain can you advise steps to add additional domains please

**Comment by acelaya** [comment]
Adding multiple domains to nginx config should be easy. The `server_name` instruction accepts as many names as you want.

`server_name example.com something.com another.com ...;`

**Comment by admecoach** [comment]
@acelaya  I had hoped that would work and added just like that a 3rd domain in /etc/nginx/conf.d/shlink.conf and then used certbot and got all 3 domains ssl and pointed correctly but as I recall it was just a blank page when I used the custom name in the https://app.shlink.io/ using domain field.  What's the best way to pull a log to id the problem if you don't mind advising me.

I'll try again and provide the nginx -t error as I couldn't find anything else online last week when this occured but remember something along the lines of too many arguments or something similar so I backed it down to just two domains.  Then I was going to try server blocks setup but chickened out.

**Comment by admecoach** [comment]
Added domains in shlink.conf, did certbot and 4 custom domains working fine.  Thanks!

**Comment by acelaya** [comment]
I'm glad to hear it's now working 🙂

**Comment by acelaya** [comment]
Locking this issue as this is just an epic.
