### ISSUE TITLE
Add support to import links from other platforms

### ISSUE THREAD

**Issue by acelaya** [shlinkio/shlink#835]
Allow importing links from other platforms:

* [x] Bit.ly https://github.com/shlinkio/shlink-importer/issues/2 (v2.4.0)
* [ ] Rebrandly
* [x] Shlink (through API) https://github.com/shlinkio/shlink-importer/issues/4 (v2.7.0)
* [x] Standard CSV https://github.com/shlinkio/shlink-importer/issues/5 (v2.6.0)

---

### Spec

Create a new `shlinkio/shlink-importer` package, providing:

* [x] Set of strategies to import from different sources, returning a generator wrapping the list of links.
* [x] CLI command which receives the source from where to import from. Based on that it will load the proper import strategy and run the proper CLI interactions (like requesting API keys, access tokens or files to import from, as well as providing information on how to get those).
* [x] The command will also expect a dependency to which it will pass the generator with the list of links. Every link will fulfil a model defined by this package. The dependency's implementation will be provided by consuming packages (shlink in this case).
* [x] The package may also "suggest" other dependencies that are required by the different strategies, which will in turn be provided by consuming packages (http clients, CSV parsers, etc).
* [x] Shlink should define a new nullable `import_source` column in the `short_urls` table, which can be used to avoid importing the same URL more than once, but still allow running the process multiple times in case it fails.
* [x] The implementation in shlink that will persist links, should show a warning, and ask what to do when an error occurs while running interactively.

### Improvements

* Import visits together with the links, when possible.

**Comment by acelaya** [comment]
To anyone seeing this, if you have a paid account for any of the services listed above, I would really appreciate getting a sample of the export file for any of them.

**Comment by ajtatum** [comment]
Do you still need an example export?

**Comment by acelaya** [comment]
If you have one from rebrandly, yes 🙂

**Comment by ajtatum** [comment]
Unfortunately, the subscription I have doesn't allow me to export links. However, I did manage to import all my links from Bitly and ran into duplicate key errors for domains and tags. I had to manually create the domains and tags in the database first and then run the import. Not a huge pain, but just a FYI. Also FYI - I've fully migrated all my links to Shlink! I've canceled Bitly and requesting a refund from Rebrandly as I'm within 30 days. Thank you for writing this. It's awesome!

**Comment by acelaya** [comment]
> Unfortunately, the subscription I have doesn't allow me to export links

No problem. Well leave that for the future 🙂 

> ran into duplicate key errors for domains and tags

That's unfortunate. I think I need to review the process.

Since tags and domains are created transparently, there's probably a missing table lock there, which would prevent race conditions. I'll check this.

> I've fully migrated all my links to Shlink! I've canceled Bitly and requesting a refund from Rebrandly as I'm within 30 days. Thank you for writing this. It's awesome!

I'm glad to hear that. Thank you for the kind words 🙂

**Comment by acelaya** [comment]
> Unfortunately, the subscription I have doesn't allow me to export links. However, I did manage to import all my links from Bitly and ran into duplicate key errors for domains and tags. I had to manually create the domains and tags in the database first and then run the import. Not a huge pain, but just a FYI. Also FYI - I've fully migrated all my links to Shlink! I've canceled Bitly and requesting a refund from Rebrandly as I'm within 30 days. Thank you for writing this. It's awesome!

Hey @ajtatum, I have found the root cause of the duplicated error you got. This should fix it https://github.com/shlinkio/shlink/pull/1068

**Comment by acelaya** [comment]
Closing this epic. If you want to track the progress of rebrandly support, subscribe to this
