### ISSUE TITLE
Ability to pass a title for the link and/or automatically generate title

### ISSUE THREAD

**Issue by ajtatum** [shlinkio/shlink#941]
Services like Bitly and Rebrandly offer the ability to pass in a title for a link, thus making reporting/UI look a bit cleaner. It's far easier to glance over a page/report and see the titles of pages rather than the long URL, but that may be just a personal preference. Either way, I think it would be nice if a title could be passed in.

For further background, for both services mentioned, if the link title isn't passed in the services use the page title. I'm not sure if they grab it from the title tags or the og:title tag. Either way, it's nice that it if it isn't provided it's automatically generated.

Let me know if you need further information or clarification.

Thank you,
AJ

---

* [x] Add new nullable title property to short URLs
* [x] Allow to provide the title while creating/updating short URLs
* [x] Document title prop in swagger docs
* [x] Add new config option to enable automatic title resolution when not provided. Should be disabled by default
* [x] Update installer to support automatic title resolution config option (https://github.com/shlinkio/shlink-installer/issues/101)
* [x] During short URL creation, allow to dynamically resolve title from long URL if configured so
* [x] During short URL edition, allow to dynamically resolve title from long URL if configured so, prev title is null or was also dynamically resolved, and no new title has been provided
* [x] Track if the title was provided or automatically resolved
* [x] Support searching short URLs list by title
* [x] Support ordering short URLs list by title
* [x] Add title field support in shlink-importer (https://github.com/shlinkio/shlink-importer/issues/21)
* [ ] Document the feature (https://github.com/shlinkio/shlink.io/issues/195)

**Comment by acelaya** [comment]
It definitely sounds like something nice to have.

Regarding the title autogeneration, I would probably make it disabled by default, allowing users to opt in through installation config or env vars, as many other features.

Just to avoid adding a new behavior for users updating from older versions.

**Comment by acelaya** [comment]
Hey @ajtatum. I have already started to implement this, and there's one use case that I'm not sure how to resolve.

It's related with the edition of short URLs. Currently Shlink allows to edit the long URL to which a short URL points, together with a few other properties.

My question is, what should happen with the title when the long URL is changed?

* Keep the title as it is, allowing to provide or resolve the title only during short URL creation.
* Try to resolve the title from the new long URL, only if there was no title previously and no new title has been provided.
* Try to resolve the title from the new long URL, only if there was no title, there was title but it was also resolved from previous long URL, and always if no new title was provided.

I tend to think the third one should be the proper one, so in case you originally provided a custom title during creation, it will be preserved, but updated in any other case.

What do you think?

**Comment by mdrxy** [comment]
Are there plans to add a `--title` option for `short-url:create`? I see some work being done relating to that method in 5bccdde.

**Comment by acelaya** [comment]
> Are there plans to add a `--title` option for `short-url:create`? I see some work being done relating to that method in 5bccdde. 

Yes, I noticed that option was missing while working on https://github.com/shlinkio/shlink/pull/2164, and took the opportunity to add it.
